import defaultMdxComponents from "fumadocs-ui/mdx";
import type { MDXComponents } from "mdx/types";
import {
  AbortSignalDemo,
  ActionsDemo,
  AnchorArrowDemo,
  AnchorClickDemo,
  AnchoredDemo,
  AnchorSidesDemo,
  CloseButtonDemo,
  CloseButtonPositionDemo,
  CloseDemo,
  CustomAnchoredDemo,
  CustomDemo,
  CustomNotificationDemo,
  DedupDemo,
  DescriptionDemo,
  EntryDirectionDemo,
  ExpandDemo,
  ExpandedLimitDemo,
  HistoryDemo,
  IconDemo,
  PositionDemo,
  PromiseDemo,
  RichColorsDemo,
  StyleDemo,
  SwipeDemo,
  TimeoutDemo,
  ToastOptionsDemo,
  TypesDemo,
  UpdateDemo,
} from "@/components/demos";

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    AbortSignalDemo,
    TypesDemo,
    DescriptionDemo,
    ActionsDemo,
    UpdateDemo,
    CloseDemo,
    CloseButtonDemo,
    CloseButtonPositionDemo,
    DedupDemo,
    EntryDirectionDemo,
    ExpandDemo,
    ExpandedLimitDemo,
    HistoryDemo,
    IconDemo,
    PositionDemo,
    PromiseDemo,
    CustomDemo,
    CustomNotificationDemo,
    CustomAnchoredDemo,
    RichColorsDemo,
    AnchoredDemo,
    AnchorSidesDemo,
    AnchorClickDemo,
    AnchorArrowDemo,
    StyleDemo,
    SwipeDemo,
    TimeoutDemo,
    ToastOptionsDemo,
    ...components,
  };
}
